### ISSUE TITLE
Doesn't build on Archlinux

### ISSUE THREAD

**Issue by ghost** [sleepingtux/TCD_COMMUNITY#3]
Hi there,

I just had to recompile and it fails.

Here's the PKGBUILD I use: https://hastebin.com/share/urafuberer.bash
Here's the output of the compilation process: https://hastebin.com/share/tojovezuve.sql

Unfortunately I'm not capable of fixing this.

The PKGBUILD worked the last time I built the package which was at commit no. 20. I haven't bisected it for now, maybe you'll see the issue in the compilation output.

Thanks mate!
sekret

**Comment by sleepingtux** [comment]
Hello,
Sorry i do not know what could be the problem, nothing change here.
I will take a look if i found something but i am not usefull for pkgbuild :/

EDIT: the error seems to be there:
build/tcd-community-git/src/tcd-community-git/main.cpp:32:45: error: expected primary-expression before ‘__attribute__’
   32 |         YAML_CPP_API::YAML::Node m_config = YAML_CPP_API::YAML::LoadFile("tcd_config.yaml");
   
 
 Same here:
 /build/tcd-community-git/src/tcd-community-git/hardwarecontrol.cpp:110:41: error: expected primary-expression before ‘__attribute__’
  110 |     YAML_CPP_API::YAML::Node m_config = YAML_CPP_API::YAML::LoadFile(p_profile);

So something related to the yaml library + gcc version

**Comment by ghost** [comment]
Yeah, there was a new yaml version which seems to change a lot.

Can you update the code so it builds again?

**Comment by sleepingtux** [comment]
Hello. 

Will try to take a look but as it works on my os (openSuse Leap), i should build a vm to have the same problem.

If i got time, i will take a look to see what i could do.

**Comment by ghost** [comment]
Ok, I fixed it myself with the help of ChatGPT. Completely didn't remember that this is an option nowadays…
[yaml-0.8-fix.zip](https://github.com/sleepingtux/TCD_COMMUNITY/files/12774266/yaml-0.8-fix.zip)

**Comment by sleepingtux** [comment]
Hello,
Thank's, it was easy in fact..
Will add the correction if it works for all the version. 

Sorry did not have time to take a look.

**Comment by sleepingtux** [comment]
Hello,

Sorry for the time needed.
I have made the modification, it should be ok for you now with no patch.
